# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\findFotopolimerArt.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Dialog.resize(543, 445)
        Dialog.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 521, 431))
        self.frame.setGraphicsEffect(
            QtWidgets.QGraphicsDropShadowEffect(
                blurRadius=25,
                xOffset=0,
                yOffset=0,
                color=QtGui.QColor(234, 221, 186, 100),
            )
        )
        self.frame.setStyleSheet(
            "QFrame{\n"
            "    border: 10px blue solid;\n"
            "    background-color: rgba(19, 174, 163, .95);\n"
            "    border-radius: 20px;\n"
            "}"
        )
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setGeometry(QtCore.QRect(70, 200, 201, 17))
        self.checkBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox.setStyleSheet("QLabel{\n" "    color: #082b28;\n" "}")
        self.checkBox.setObjectName("checkBox")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 50, 521, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(
            "QLabel{\n" "    color: #082b28;\n" "    background-color: none;\n" "}"
        )
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(60, 340, 401, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton.setStyleSheet(
            "QPushButton{\n"
            "border-radius:10px;\n"
            "background-color: #114541;\n"
            "font-weight: bold;\n"
            "color: #FFF;\n"
            "\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "background-color: #082b28;\n"
            "\n"
            "}"
        )
        self.pushButton.setAutoDefault(True)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(60, 150, 401, 51))
        self.frame_2.setStyleSheet("QFrame{\n" "    background-color: none;\n" "}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setStyleSheet(
            "QLabel{\n" "    color: #082b28;\n" "    font-weight: 500;\n" "}"
        )
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        # self.lineEdit_2.setStyleSheet(
        #     "QLineEdit{\n"
        #     "    padding: 4px 10px;\n"
        #     "    font-size: 12px;\n"
        #     "    font-weight: 400;\n"
        #     "    line-height: 1.5px;\n"
        #     "    color: #212529;\n"
        #     "    background-color: #fff;\n"
        #     "    background-clip: padding-box;\n"
        #     "    border: 1px solid #ced4da;\n"
        #     "    border-radius: 6px;\n"
        #     "}"
        # )
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(60, 230, 401, 61))
        self.frame_3.setStyleSheet("QFrame{\n" "    background-color: none;\n" "}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setStyleSheet(
            "QLabel{\n" "    color: #082b28;\n" "    font-weight: 500;\n" "}"
        )
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_3)
        # self.lineEdit_3.setStyleSheet(
        #     "QLineEdit{\n"
        #     "    padding: 4px 10px;\n"
        #     "    font-size: 12px;\n"
        #     "    font-weight: 400;\n"
        #     "    line-height: 1.5px;\n"
        #     "    color: #212529;\n"
        #     "    background-color: #fff;\n"
        #     "    background-clip: padding-box;\n"
        #     "    border: 1px solid #ced4da;\n"
        #     "    border-radius: 6px;\n"
        #     "}"
        # )
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(60, 90, 401, 51))
        self.frame_4.setStyleSheet("QFrame{\n" "    background-color: none;\n" "}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setStyleSheet(
            "QLabel{\n" "    color: #082b28;\n" "    font-weight: 500;\n" "}"
        )
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit.setStyleSheet(
            "QLineEdit{\n"
            "    padding: 4px 10px;\n"
            "    font-size: 12px;\n"
            "    font-weight: 400;\n"
            "    line-height: 1.5px;\n"
            "    color: #212529;\n"
            "    background-color: #fff;\n"
            "    background-clip: padding-box;\n"
            "    border: 1px solid #ced4da;\n"
            "    border-radius: 6px;\n"
            "}"
        )
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_2.setGeometry(QtCore.QRect(70, 290, 201, 17))
        self.checkBox_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_2.setStyleSheet("QLabel{\n" "    color: #082b28;\n" "}")
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 380, 501, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(
            "QLabel{\n" "    color: #f6d55c;\n" "    background-color: none;\n" "}\n" ""
        )

        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(10, 403, 501, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(
            "QLabel{\n" "    color: #f6d55c;\n" "    background-color: none;\n" "}\n" ""
        )

        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(460, 20, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_2.setStyleSheet(
            "QPushButton{\n"
            "border-radius:10px;\n"
            "background-color: #114541;\n"
            "font-weight: bold;\n"
            "color: #FFF;\n"
            "\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "background-color: #082b28;\n"
            "\n"
            "}"
        )
        self.pushButton_2.setAutoDefault(True)
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.checkBox.setText(_translate("Dialog", "Cambiar ruta de busqueda"))
        self.label.setText(
            _translate("Dialog", "Encuentra los artes de los fotopolimeros")
        )
        self.pushButton.setText(_translate("Dialog", "Buscar Items"))
        self.label_3.setText(_translate("Dialog", "Ruta"))
        self.label_4.setText(_translate("Dialog", "Destinatarios"))
        self.label_2.setText(_translate("Dialog", "Items"))
        self.checkBox_2.setText(_translate("Dialog", "Cambiar destinatarios"))
        self.label_5.setText(_translate("Dialog", ""))
        self.pushButton_2.setText(_translate("Dialog", "X"))
