# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Find FP\progressBar.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QApplication


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.resize(300, 127)
        # Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        Form.setStyleSheet("QLabel{background-color: transparent;}")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 10, 281, 111))
        self.frame.setStyleSheet(
            "QFrame{\n"
            "    background-color: rgba(19, 174, 163, .95);\n"
            "    border-radius: 20px;\n"
            "}"
        )
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setObjectName("frame")
        self.frame.setGraphicsEffect(
            QtWidgets.QGraphicsDropShadowEffect(
                blurRadius=25,
                xOffset=0,
                yOffset=0,
                color=QtGui.QColor(234, 221, 186, 100),
            )
        )
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(
            "QLabel{\n" "    background-color: transparent;\n" "    color: #fff;\n" "}"
        )
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(30, 50, 231, 21))
        self.progressBar.setStyleSheet("QProgressBar {\n" "    color: #fff;\n" "}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Buscando..."))


class ProgressBar(QWidget):
    def __init__(self) -> None:
        super().__init__()
        self.ui = Ui_Form()
        self.ui.setupUi(self)


if __name__ == "__main__":
    app = QApplication(sys.argv)

    form = ProgressBar()
    form.show()

    sys.exit(app.exec_())
